# Example for trying the algorithm and basic use of it

In [9]:
from SMILE.smile_ import SMiLE
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import KFold
import numpy as np

## Generate the data

In [10]:
X, y = make_multilabel_classification(n_samples=700)
X

array([[5., 1., 0., ..., 0., 0., 1.],
       [4., 2., 6., ..., 1., 2., 2.],
       [3., 3., 4., ..., 4., 1., 3.],
       ...,
       [2., 4., 3., ..., 1., 1., 1.],
       [3., 5., 2., ..., 3., 3., 1.],
       [5., 1., 7., ..., 3., 0., 7.]])

## Create the model and initialize it with the parameters we want

In [11]:
smile = SMiLE(s=0.5, alpha=0.35, k=5)

## Generate the partitions of the data for training and predict

In [12]:
skf = KFold(n_splits=2)
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

print(X_train)
print(X_test)

[[5. 1. 0. ... 0. 0. 1.]
 [4. 2. 6. ... 1. 2. 2.]
 [3. 3. 4. ... 4. 1. 3.]
 ...
 [3. 1. 4. ... 0. 1. 1.]
 [1. 1. 1. ... 4. 2. 1.]
 [5. 2. 5. ... 2. 3. 2.]]
[[3. 2. 3. ... 6. 3. 2.]
 [5. 5. 1. ... 2. 1. 4.]
 [1. 3. 1. ... 1. 1. 1.]
 ...
 [2. 4. 3. ... 1. 1. 1.]
 [3. 5. 2. ... 3. 3. 1.]
 [5. 1. 7. ... 3. 0. 7.]]


## Now we will train our model and predict, to compare the results

In [13]:
#This algorithm works with columns rather than with rows
X_train = np.transpose(X_train)
y_train = np.transpose(y_train)
X_test = np.transpose(X_test)
smile.fit(X_train, y_train)
predictions = smile.predict(X_test)
print(predictions)
print(y_test)

(5, 1)
array([[2.46583312, 1.38658774, 1.9515829 , 1.35493632, 2.26174591],
       [2.72918315, 1.64993777, 2.21493294, 1.61828636, 2.52509595],
       [2.5427411 , 1.46349572, 2.02849089, 1.43184431, 2.3386539 ],
       ...,
       [2.64413146, 1.56488608, 2.12988124, 1.53323466, 2.44004425],
       [2.61222506, 1.53297968, 2.09797484, 1.50132827, 2.40813785],
       [2.8285126 , 1.74926722, 2.31426239, 1.71761581, 2.62442539]])
array([[0, 1, 1, 1, 1],
       [1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0],
       ...,
       [0, 1, 0, 0, 0],
       [1, 1, 0, 1, 0],
       [0, 0, 0, 1, 0]])
