# Example for trying the algorithm and basic use of it

In [1]:
from SMILE.smile_ import SMiLE
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import KFold
import numpy as np

## Generate the data

In [2]:
X, y = make_multilabel_classification(n_samples=700)
X

array([[4., 5., 1., ..., 4., 1., 3.],
       [1., 3., 3., ..., 1., 1., 0.],
       [2., 3., 0., ..., 2., 2., 2.],
       ...,
       [0., 4., 0., ..., 1., 1., 5.],
       [0., 1., 6., ..., 0., 1., 6.],
       [5., 3., 4., ..., 0., 2., 5.]])

## Create the model and initialize it with the parameters we want

In [3]:
smile = SMiLE(s=0.5, alpha=0.35, k=5)

## Generate the partitions of the data for training and predict

In [4]:
skf = KFold(n_splits=2)
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

print(X_train)
print(X_test)

[[4. 5. 1. ... 4. 1. 3.]
 [1. 3. 3. ... 1. 1. 0.]
 [2. 3. 0. ... 2. 2. 2.]
 ...
 [4. 1. 3. ... 0. 4. 2.]
 [3. 1. 5. ... 1. 5. 3.]
 [3. 3. 2. ... 3. 4. 3.]]
[[6. 3. 3. ... 3. 1. 3.]
 [2. 5. 4. ... 6. 3. 0.]
 [0. 3. 3. ... 2. 2. 5.]
 ...
 [0. 4. 0. ... 1. 1. 5.]
 [0. 1. 6. ... 0. 1. 6.]
 [5. 3. 4. ... 0. 2. 5.]]


## Now we will train our model and predict, to compare the results

In [5]:
#This algorithm works with columns rather than with rows
X_train = np.transpose(X_train)
y_train = np.transpose(y_train)
X_test = np.transpose(X_test)
smile.fit(X_train, y_train)
predictions = smile.predict(X_test)
print(predictions)
print(y_test)

(5, 1)
[[0.62444236 1.82606465 0.82689403 0.83417465 0.65312862]
 [0.68608559 1.88770788 0.88853726 0.89581789 0.71477186]
 [0.68965568 1.89127797 0.89210736 0.89938798 0.71834195]
 ...
 [0.64560233 1.84722462 0.848054   0.85533462 0.67428859]
 [0.56547503 1.76709732 0.7679267  0.77520732 0.59416129]
 [0.68037656 1.88199885 0.88282823 0.89010885 0.70906282]]
[[1 0 0 0 0]
 [0 0 0 1 1]
 [0 1 1 1 1]
 ...
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
