# Example for trying the algorithm and basic use of it

In [1]:
from SMILE.smile_ import SMiLE
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import KFold
from functions import readDataFromFile
import numpy as np

## Generate the data

In [2]:
x_train, y_train = readDataFromFile('data/CAL5000.train')
x_test, y_test = readDataFromFile('data/CAL5000.gen')
print x_train

  (0, 0)	0.08254
  (0, 1)	0.048394
  (0, 2)	0.322451
  (0, 3)	0.099049
  (0, 4)	-73.856273
  (0, 5)	2.538128
  (0, 6)	2.72329
  (0, 7)	1.110571
  (0, 8)	1.154735
  (0, 9)	0.714657
  (0, 10)	0.653754
  (0, 11)	0.596543
  (0, 12)	0.7319
  (0, 13)	0.247547
  (0, 14)	0.731591
  (0, 15)	0.522678
  (0, 16)	0.176512
  (0, 17)	0.067492
  (0, 18)	0.055001
  (0, 19)	0.369305
  (0, 20)	0.043764
  (0, 21)	6.096384
  (0, 22)	1.972327
  (0, 23)	1.281913
  (0, 24)	1.193782
  :	:
  (446, 43)	0.352598
  (446, 44)	0.477449
  (446, 45)	0.3917
  (446, 46)	0.392415
  (446, 47)	0.445219
  (446, 48)	0.479271
  (446, 49)	0.465497
  (446, 50)	0.517615
  (446, 51)	0.012705
  (446, 52)	0.014322
  (446, 53)	0.047956
  (446, 54)	0.03165
  (446, 55)	1.815593
  (446, 56)	0.328488
  (446, 57)	0.250294
  (446, 58)	0.206286
  (446, 59)	0.133358
  (446, 60)	0.128053
  (446, 61)	0.1246
  (446, 62)	0.131482
  (446, 63)	0.127403
  (446, 64)	0.107976
  (446, 65)	0.11156
  (446, 66)	0.14343
  (446, 67)	0.171373


## Create the model and initialize it with the parameters we want

In [3]:
smile = SMiLE(s=0.5, alpha=0.35, k=5)

## Now we will train our model and predict, to compare the results

In [4]:
#This algorithm works with columns rather than with rows
x_train = np.transpose(x_train.todense())
y_train = np.transpose(y_train)
x_test = np.transpose(x_test.todense())
smile.fit(x_train, y_train)
predictions, predictionsNormalized = smile.predict(x_test)
print predictions.shape
print predictionsNormalized.shape
print y_test.shape
print(np.transpose(predictions))
print(np.transpose(predictionsNormalized))
print(y_test)

[[1.         1.01843405 0.95205864 ... 1.03144801 1.01594844 0.98366139]
 [0.93973086 0.95816492 0.8917895  ... 0.97117887 0.95567931 0.92339225]
 [0.898243   0.91667706 0.85030164 ... 0.92969101 0.91419145 0.88190439]
 ...
 [0.12554688 0.14398093 0.07760551 ... 0.15699489 0.14149532 0.10920826]
 [0.13680679 0.15524085 0.08886543 ... 0.1682548  0.15275524 0.12046818]
 [0.15346853 0.17190258 0.10552716 ... 0.18491654 0.16941697 0.13712992]]
[1.         0.95816492 0.85030164 0.77936095 0.67625617 0.85934903
 0.71256619 0.68635129 0.64419827 0.65507194 0.60453248 0.65478396
 0.64367776 0.52942505 0.56273861 0.5927628  0.56224247 0.55627037
 0.52356187 0.55745294 0.48687288 0.58784776 0.45331459 0.63185335
 0.59023071 0.40599187 0.48117428 0.47103376 0.51835583 0.39836016
 0.38187902 0.60239709 0.44278723 0.55241124 0.3986745  0.57390165
 0.41199522 0.28127773 0.28182091 0.2947815  0.40127491 0.29501813
 0.29808219 0.28313736 0.29305227 0.28302346 0.2968483  0.29492421
 0.25970459 0.300268