# Example for trying the algorithm and basic use of it

In [1]:
from SMILE.smile_ import SMiLE
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import KFold
import numpy as np

## Generate the data

In [2]:
X, y = make_multilabel_classification(n_samples=700)
X

array([[1., 3., 5., ..., 3., 5., 4.],
       [1., 3., 0., ..., 1., 1., 2.],
       [2., 1., 5., ..., 1., 0., 6.],
       ...,
       [2., 2., 3., ..., 0., 1., 2.],
       [2., 4., 3., ..., 0., 5., 0.],
       [4., 6., 0., ..., 2., 5., 1.]])

## Create the model and initialize it with the parameters we want

In [3]:
smile = SMiLE(s=0.5, alpha=0.35, k=5)

## Generate the partitions of the data for training and predict

In [4]:
skf = KFold(n_splits=2)
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

print(X_train)
print(X_test)

[[1. 3. 5. ... 3. 5. 4.]
 [1. 3. 0. ... 1. 1. 2.]
 [2. 1. 5. ... 1. 0. 6.]
 ...
 [3. 4. 0. ... 3. 3. 4.]
 [3. 3. 2. ... 3. 1. 0.]
 [2. 2. 6. ... 0. 6. 1.]]
[[4. 1. 2. ... 2. 1. 2.]
 [4. 1. 1. ... 4. 0. 3.]
 [3. 1. 1. ... 0. 4. 2.]
 ...
 [2. 2. 3. ... 0. 1. 2.]
 [2. 4. 3. ... 0. 5. 0.]
 [4. 6. 0. ... 2. 5. 1.]]


## Now we will train our model and predict, to compare the results

In [5]:
#This algorithm works with columns rather than with rows
X_train = np.transpose(X_train)
y_train = np.transpose(y_train)
X_test = np.transpose(X_test)
smile.fit(X_train, y_train)
predictions1, predictions2 = smile.predict(X_test)
print(y_train)
print(np.transpose(predictions1))
print(np.transpose(predictions2))
print(y_test)

[[0.996875   0.640625   0.421875   0.534375   0.209375  ]
 [0.52295918 0.99744898 0.42091837 0.51785714 0.22193878]
 [0.54       0.66       0.996      0.484      0.268     ]
 [0.53773585 0.63836478 0.38050314 0.99685535 0.21069182]
 [0.50757576 0.65909091 0.50757576 0.50757576 0.99242424]]
[[1.         1.         0.         ... 1.         1.         1.        ]
 [0.4855643  0.34117647 0.         ... 0.51       1.         1.        ]
 [1.         0.26517984 0.         ... 0.40410418 1.         0.2481203 ]
 [0.26976852 1.         0.         ... 1.         0.34161491 0.22115645]
 [0.26923637 0.16300155 0.         ... 0.2583572  0.33378988 0.21068205]]
[[1 0 0 ... 1 1 0]
 [0 0 0 ... 0 1 1]
 [1 0 0 ... 0 1 0]
 [0 1 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
[[0.92695292 0.72916893 0.61951905 0.63327633 0.47403053]
 [0.93958859 0.7418046  0.63215473 0.64591201 0.48666621]
 [0.90751157 0.70972758 0.60007771 0.61383499 0.45458919]
 ...
 [0.89240112 0.69461713 0.58496725 0.59872453 0.43947873]
 [0.942141