# Example for trying the algorithm and basic use of it

In [1]:
from SMILE.smile_ import SMiLE
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import KFold
import numpy as np

## Generate the data

In [2]:
X, y = make_multilabel_classification(n_samples=700)
X

array([[3., 1., 3., ..., 2., 7., 2.],
       [3., 3., 4., ..., 3., 1., 0.],
       [2., 0., 2., ..., 4., 2., 1.],
       ...,
       [3., 4., 1., ..., 1., 1., 5.],
       [2., 1., 6., ..., 2., 0., 4.],
       [6., 5., 1., ..., 2., 2., 2.]])

## Create the model and initialize it with the parameters we want

In [3]:
smile = SMiLE(s=0.5, alpha=0.35, k=5)

## Generate the partitions of the data for training and predict

In [4]:
skf = KFold(n_splits=2)
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

print(X_train)
print(X_test)

[[3. 1. 3. ... 2. 7. 2.]
 [3. 3. 4. ... 3. 1. 0.]
 [2. 0. 2. ... 4. 2. 1.]
 ...
 [0. 0. 0. ... 0. 2. 3.]
 [0. 3. 1. ... 1. 5. 3.]
 [2. 0. 3. ... 1. 1. 8.]]
[[1. 3. 2. ... 2. 0. 2.]
 [2. 3. 2. ... 5. 2. 2.]
 [2. 4. 1. ... 1. 0. 0.]
 ...
 [3. 4. 1. ... 1. 1. 5.]
 [2. 1. 6. ... 2. 0. 4.]
 [6. 5. 1. ... 2. 2. 2.]]


## Now we will train our model and predict, to compare the results

In [5]:
#This algorithm works with columns rather than with rows
X_train = np.transpose(X_train)
y_train = np.transpose(y_train)
X_test = np.transpose(X_test)
smile.fit(X_train, y_train)
predictions1, predictions2 = smile.predict(X_test)
print(predictions1)
print(predictions2)
print(y_test)

[[0.         1.         0.         ... 1.         0.         1.        ]
 [0.         0.53434226 0.         ... 0.50799508 0.         0.50799508]
 [0.         1.         0.         ... 0.38158611 0.         0.38158611]
 [0.         0.6322502  0.         ... 0.7732259  0.         0.7732259 ]
 [0.         0.30688199 0.         ... 1.         0.         1.        ]]
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
[[0 1 1 0 1]
 [0 1 1 0 0]
 [0 0 0 0 0]
 ...
 [0 1 1 0 0]
 [0 0 0 0 1]
 [0 0 1 0 1]]
