# Example for trying the algorithm and basic use of it

In [1]:
from SMILE.smile_ import SMiLE
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import KFold
from functions import readDataFromFile
import numpy as np

## Generate the data

In [2]:
x_train, y_train = readDataFromFile('data/CAL5000.train')
x_test, y_test = readDataFromFile('data/CAL5000.gen')
print x_train

  (0, 0)	0.08254
  (0, 1)	0.048394
  (0, 2)	0.322451
  (0, 3)	0.099049
  (0, 4)	-73.856273
  (0, 5)	2.538128
  (0, 6)	2.72329
  (0, 7)	1.110571
  (0, 8)	1.154735
  (0, 9)	0.714657
  (0, 10)	0.653754
  (0, 11)	0.596543
  (0, 12)	0.7319
  (0, 13)	0.247547
  (0, 14)	0.731591
  (0, 15)	0.522678
  (0, 16)	0.176512
  (0, 17)	0.067492
  (0, 18)	0.055001
  (0, 19)	0.369305
  (0, 20)	0.043764
  (0, 21)	6.096384
  (0, 22)	1.972327
  (0, 23)	1.281913
  (0, 24)	1.193782
  :	:
  (446, 43)	0.352598
  (446, 44)	0.477449
  (446, 45)	0.3917
  (446, 46)	0.392415
  (446, 47)	0.445219
  (446, 48)	0.479271
  (446, 49)	0.465497
  (446, 50)	0.517615
  (446, 51)	0.012705
  (446, 52)	0.014322
  (446, 53)	0.047956
  (446, 54)	0.03165
  (446, 55)	1.815593
  (446, 56)	0.328488
  (446, 57)	0.250294
  (446, 58)	0.206286
  (446, 59)	0.133358
  (446, 60)	0.128053
  (446, 61)	0.1246
  (446, 62)	0.131482
  (446, 63)	0.127403
  (446, 64)	0.107976
  (446, 65)	0.11156
  (446, 66)	0.14343
  (446, 67)	0.171373


## Create the model and initialize it with the parameters we want

In [3]:
smile = SMiLE(s=0.5, alpha=0.35, k=5)

## Now we will train our model and predict, to compare the results

In [4]:
#This algorithm works with columns rather than with rows
x_train = np.transpose(x_train.todense())
y_train = np.transpose(y_train)
x_test = np.transpose(x_test.todense())
print y_test
smile.fit(x_train, y_train)
predictions, predictionsNormalized = smile.predict(x_test)

[[1 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]
1.7381801683086238
1.851500835514611
3.5483243814228462
1.9841105817027418
3.061417411141491
3.5608056894615516
4.809380333308222
2.186090592865937
3.6738874385977196
4.32897277445388
2.3733737615331574
1.1545364850307043
2.41218482994042
3.6032716480096827
2.4935711513939274
1.1679585641052117
1.9872070426177302
2.28041717053321
1.9030861869992248
5.011823587328779
1.5169749351832702
2.66758972707193
1.1330355847873244
2.4119303213280636
1.6802531617242051
2.101911002490903
1.7490461214793238
1.4561333958343539
2.7602481391210594
1.6994817097765917
3.932284996719233
1.7859618808762718
1.5474373323829607
2.918350180934351
2.421510309851877
0.8802887373271128
1.3068503332593358
2.154467596267775
2.45385749189241
2.433540318653057
1.859771536887839
3.3809767445893733
3.156226681424586
2.420950393731424
2.1559117076866943
4.227157313841953
2.789002117260469
2.62760736721

5.341548032227187
6.892341841082036
7.4532939628342865
5.939968315936486
5.87252891123066
5.59110828398078
7.083460975157996
4.401439732206878
5.624331732015306
10.112154984282501
5.20036514848508
9.398311310793154
8.904070669972795
5.99924806808279
10.795048823916977
8.784874834861341
7.711270603736847
5.041405479055179
7.928746558320799
4.418182973812095
4.569020980729508
3.966829129553213
7.3148200276272854
7.72548555081001
5.92819232101332
9.589468659235614
5.335072639760103
6.633329483051692
5.772537836025723
5.798545666061246
5.430589718088035
6.619205283177893
6.758810887927111
6.133683015608504
3.315394102565829
4.537371225677848
3.041255754173946
9.63040915602968
7.61592972097197
7.729266722576248
2.9286174307760526
5.626992058367319
4.943401087998417
4.346883217980815
3.835165359555726
4.485925583836768
4.204065501103626
7.605404041102681
4.289569229542824
3.205951054556718
3.8204488379378168
8.245461532569156
8.909309024352861
4.483533758581332
6.7226421738589535
3.033267333

6.301922198603073
4.099971101113982
4.569449370410604
5.49654128782989
3.6680282988743604
4.633024062912987
4.026419143145395
4.4555105387983645
3.899084419987511
3.1918224158452975
3.745480180401496
6.252073800431791
7.25192011942276
3.3399618531297293
3.7246888146535064
4.115766975443723
5.623642670009541
5.6469258333135794
4.517608290421353
4.662600803406118
4.349364792370981
4.853822908067692
3.5506057316339086
3.5867913675922742
3.4930353087182398
4.818006258138352
5.790365397346065
2.722229311699299
3.854051403065772
4.20318426328129
5.366741849115527
6.383452771049585
4.530664503582662
8.221712539470845
7.829390030397397
4.454976519913635
7.1122135921889065
3.9518485350346504
3.3087437387967107
4.232562392527491
5.0147093916521435
3.9821341694118733
6.201830476160147
4.857493333560235
5.771122913576425
6.444649547241592
6.182284765218824
7.23527770875673
4.290272750593181
4.65621369253243
2.803306732350457
5.162294265889231
5.202724377979484
3.820149007600943
6.400406099496614
5

5.952614145515967
7.884397096865109
9.83682431491592
8.287271350907211
5.994137474951112
8.711762417825337
8.60416895459416
7.5400758229913425
10.240501033891604
8.920102195414273
9.296249672522215
7.054875325979856
4.52816592320068
10.620753004805792
6.804000517304832
6.622605599151502
7.962549066101097
6.845547762863628
8.214854110728922
10.037681340255936
6.252376948311058
9.20035184859021
5.067722517954291
6.798040485187789
8.855049409689792
10.252367160438485
8.414227346976144
7.29016144600062
6.069257926274759
4.80366123196254
7.296379870528834
5.560414212032031
5.351819963112133
6.328603974466363
10.230671797142836
6.277180101789062
6.771830339022182
9.786923355191837
8.00905027590284
11.717450162226807
7.890411785152953
9.042098018103335
7.00631131605914
7.0917349737098485
5.105314586039925
5.5892693686592025
7.650700374144424
7.466629793567559
4.213548775787506
7.641358754428953
4.503605208913307
5.010064654938438
12.035550807202547
11.655683673609499
7.2748774199458985
5.7451

0.3127096715401891
0.20678217919620634
0.39344415361095153
0.21396343524658473
0.8168443250442923
0.24201603889613793
0.3075441629922554
0.2952086241530255
0.17876516821801303
0.25050347542576845
0.6657740758799975
0.2759469025892528
0.3919448149138929
0.38206438460817543
0.6729505894976204
0.2023034022584161
0.34999754979188236
0.24797683269110465
0.21593707434229065
0.2657402093929292
0.9294516743990153
0.5021167536381337
0.26554113514822375
0.6205718359861807
0.6631424314807859
0.3402843551274931
0.3495805374493831
0.4358940334796843
0.497102585425218
0.7247521231084956
0.32285249902949975
0.2533779599325017
0.14391282395394372
0.6263230962622449
0.34637181396623573
0.508534987791272
0.4392118372979591
0.2670648849092845
0.36492472920938324
0.563051080622189
0.7121212146707309
0.5045209514230189
0.6646924930043574
0.24524365109260593
0.5659117921092156
0.4652500881301319
0.27542308056386244
0.17104939469731556
0.37272272711682464
0.35618911308054946
0.2631964184681983
0.296203719676

0.5064070542319135
0.3172760668823588
0.430796993831661
0.4658054253454093
0.7373372298659625
0.484277724040525
0.756956604055391
0.6397135584728264
0.3103479306787326
0.5045109791344807
0.36506952024489014
0.6767697377395139
0.45357571758072934
0.5848107926613921
0.4886660676192679
0.6106249328236616
0.4513810804440036
0.5195333821913465
0.7164615322666097
0.2985423191384579
0.9387709490882357
0.35522114746182554
0.3558706236504248
0.4030162234843368
0.32538766338634073
0.4105277389859545
0.6511613511150869
0.4498454519524977
0.3847034128224167
0.5746717928996593
0.8006540381741143
0.40285858823117304
0.4278030411328688
0.3507134897225652
0.5806071653716448
0.7203492418573716
0.7306357142215758
0.45470429571783744
0.5613292419851291
0.8232210377234614
0.8067591709859632
0.41462609399084605
0.48487036424730967
0.9130736984417289
0.5643254210973573
0.8608741125284567
0.5611163109314872
0.4387907328033697
0.3091671486191968
0.5822237053091792
0.6487919182721589
0.7822943669535352
0.53035

1.8710228122772459
1.9302104096316655
1.0553765632440297
2.9177089243865897
1.496866037361054
1.5646165534661014
1.3196787591805972
1.6593525521929253
1.342386669169301
0.639638037683053
2.061196456835451
1.1837236717378752
1.7840668146145329
0.8131683574591486
0.6000947507788131
2.2680704024757192
0.6549164392202276
1.8926950970838883
1.660563928770316
1.100097515635352
0.6522361729466635
2.6007234201208096
1.8872458807131918
0.881973675707874
1.1276752984797023
2.299700247417922
1.3549438753038316
1.0020768656438617
1.4750087915918737
1.320515600163489
0.9258614052759433
1.2772768375312047
2.1332493791579408
1.7027152868588848
0.7017987353932217
0.9132510998016321
0.6770567627028174
1.2891402602207602
1.9072033849248013
0.9030010253956622
1.234384641920416
0.8043702395184499
1.3400114061507304
1.7323761977862335
0.6750716747035652
2.1046016027049523
1.938485909138741
1.0452080013044829
1.2154374150825111
2.1210094466962275
0.9577578053094529
2.4998686779504693
2.2629985442374663
0.97

1.113427969288039
1.2694030964724399
1.4866564787342775
2.6630622706624845
1.3085538543023465
2.0282922400847747
1.5093745004479526
1.9509317720186758
1.5987565403652089
1.8327200715714371
2.818166829034699
1.1680295212162033
2.728591237725948
1.220335555668666
0.8492490283644483
1.6063271278189197
1.5040428257165668
1.436869157567471
1.6776395706074934
1.8220810069283249
1.3230420158447602
1.9643178586356003
2.9668310127190263
1.6002983280212089
1.1316133373194255
1.3647080982082689
2.919018364977993
1.8791807364553186
1.4233900371838597
1.8151208464146906
1.9709806278944288
1.8824373583422989
1.1356145691714667
2.101525820132976
3.0839405243230718
1.8509706338685072
1.7545298462847403
1.294370848283953
1.3209384772878756
2.7537974161543888
1.4107263740225167
1.2378806610210624
1.5466487182827349
2.0036900543469844
2.2544895768455677
1.533670918047068
4.2153326079784135
1.503659091502989
1.8213256048230342
1.57889764665711
0.8343231831025852
1.9132250393875043
2.2052721929729047
1.573

0.8006163768883093
0.8101698543062678
1.2906080956265504
1.3678675206720081
0.6123854195049769
1.5897126617113388
1.4713628961440433
1.109586645773338
1.6178151150614408
1.1954152604894261
0.6833052196135809
1.005351694047305
1.3611285331699885
1.023754220261429
0.70013210655218
0.8626856731354211
1.0892658789544927
1.0823288220738203
1.1812452152565949
0.9349529717421174
0.9392689591298844
0.9866904345062315
1.251518809493127
1.0437412995585795
1.723958928578964
1.171512095137625
0.8215868274886905
0.8911475075319604
1.0719282865174211
1.3194024935026503
1.1383589187333536
1.1414522615750844
1.2538634469265213
1.0252169743177875
1.7230678462632039
0.8183551384026042
0.8449897240049656
0.9834411251532216
1.2046144487159474
0.9095950373193702
1.4720221895755583
0.8229710484962429
1.0154631193903896
1.013976800911343
0.9076591847129492
1.617848833211405
2.355554213627358
1.0350908833513082
0.6569777730812313
0.899237690931639
1.025428423640078
1.001565370054711
0.7476493083724396
0.71687

5.662192593975048
4.004372198316686
5.073163939196268
5.980367273906171
4.463480801247889
7.977949586926627
3.7669356943162855
5.105358405141166
6.833515008688331
4.176843165601986
6.73395307041119
4.841238791471839
3.967898213800474
3.6505622338161157
3.1545093466772727
5.4577157881164995
6.767939444559861
5.302715965489897
2.8512498927099887
3.549399877205412
5.036460902764404
5.012497281863749
3.584886077710814
3.9245279677646705
3.4067715618538026
4.391844761431527
4.002588291212845
5.32388721936537
5.30365496886837
6.127320075786576
5.155006018695056
4.6338781937163915
5.881231737935035
5.371354546508436
4.252696244523163
4.41960948472955
6.802176043291814
5.499577237896965
4.805594833463211
7.65584627577479
8.040512017759784
2.4600291668499294
4.041119244040656
3.7869658902409835
4.039262722818313
5.145673785531574
6.805462958293033
5.068780957935185
3.633242712802839
6.749006702431072
5.0441558768559975
5.341268127845366
4.262051307247136
5.313683903184434
5.0705971830535415
4.4

1.2721493097456569
0.6498808748240921
2.021387486274013
1.737986683043056
1.3271632381374276
1.0816276117452603
1.1546999891452567
2.235539633398514
2.015702451569647
1.8873255540134155
1.342580493072922
1.187186542279246
1.3125094575295402
1.8512937274426942
1.0098576164055046
1.301179011321108
1.4826264579825035
2.3030509174142884
1.7209585364707505
1.440230347142888
0.928937059600352
1.1379987686781605
1.3715340744485192
1.1749825138674288
0.9916648100126289
1.1741580300069927
1.8001485427025428
1.8738028258731818
1.850192847265362
1.4119701600332724
1.3147487660773471
0.909555230634554
1.6795180716855915
1.9990234721153177
0.7215861871511136
1.6947000652886677
2.8423195981370455
0.9521771943955533
0.9349885591112979
1.1139317500549333
1.231691413123248
1.7636132828569733
2.3627903188023938
1.108581609895714
1.059809124940204
1.4130581893357153
0.9612973490794007
2.2943322800299852
1.4010735040213875
1.2949921801389381
2.2892272103413873
2.429143075983874
1.0567760811270652
1.316228

3.6409700585028695
2.402708191109766
3.8810478916052564
1.8342750076638452
4.7163494470473335
4.76423960658603
3.543037495013376
3.1451013080238392
2.700888325597412
3.5836103849127245
3.7780461960401066
4.282983111123199
3.4983982851643827
4.555931580799959
3.3098049023930955
4.616577418250467
1.8958817226114877
2.827042570274773
5.158019084451793
3.665853103620112
4.639955324054087
3.357322123710485
3.0493756098007605
2.3512070384438104
2.422584398607457
5.055746924560326
5.9665906879420785
3.7239553215827415
3.1929571602820737
2.9984823619527936
3.525491417886205
4.893612759702943
4.564290786647648
5.939572260903633
3.6983550139562182
3.869054486608513
3.8048586378540565
4.922349348939536
3.519241150945363
2.8776586115383065
4.733330384666956
5.150097912797402
2.2743938483869086
4.921467542802734
4.636757590279062
5.338857714632111
4.551923666301347
5.212255344643536
7.943320354400173
3.1268849804599594
3.4350866309761807
2.9844313229725437
6.2663253569049875
6.128004494770751
4.121

4.271247756721143
4.640738309958714
3.07942468157178
4.90009527352265
3.932470507720287
2.212735936453047
2.8236271930645374
5.026674106536815
3.122389136021839
3.5125501385222
4.08107648015528
2.69972432202211
3.1903993056829734
6.3503307562148885
6.3818228036136535
4.738412646848588
5.430777388570787
3.907801825781454
2.139438742881871
7.132565919471625
2.317960259598173
3.6626173952611794
4.206199611098043
6.608310398745555
2.9451572684585146
3.927664636345789
5.847393126849978
3.387234596076018
1.4636309618592427
5.487650607831906
3.6306407557326077
3.215935535527013
3.8626074943397235
4.956659070668932
2.8074435164711806
4.502336586987017
2.8595234907938125
2.614298017090829
3.5324431247885135
2.826665241526288
2.1887083581308135
2.1892299859844977
2.091201356818328
8.313527296822318
2.7009285147042954
2.2624548565912574
2.8933056873702627
2.5340221759865615
2.3610652110771744
4.835294988548702
2.017874526954229
6.6879731354017675
2.1763983299886203
2.9933791080676837
5.4733409133

4.610991646139775
4.3861398189846845
4.0010703780562435
6.084876348238719
6.226609091692855
7.121610399476036
3.328982690900312
4.233165561618627
3.2796435106668467
8.816663554107873
5.850936439521425
6.456988879788151
3.5866092886896697
4.657285748401855
6.92494231517918
4.081109431476637
5.043898674456149
3.0685309251364674
8.702666430269705
5.838380908785555
3.223009965573339
4.301489876790784
2.8235498717473444
2.6455144405419166
3.4643175354374067
4.143892311895502
3.9621704233809236
4.8634119341013395
2.972982633245737
4.526757121335818
3.3917991836597743
4.853717434884648
8.833692094542343
3.68170202144461
4.498212248101638
2.19728729455909
5.363073324620196
5.606422663723848
3.5455449766393663
8.542432676909268
8.709618223733628
4.288702824921715
3.383239982806953
4.026568068254665
6.004508459871271
4.6561033043098785
4.234552909244934
3.3319853836164177
3.2530004847493954
8.320963792382084
2.13333002104255
3.642318618289992
4.890741524732782
2.2911814969935325
3.19476302109848

3.437121856202312
2.736019360305433
2.647010172104983
2.8915166788870437
7.454747308701942
2.373739879872896
2.8957119576254655
2.6324739863859103
2.4332012591043375
3.569297084205782
5.00505798879256
3.4859109488436566
3.132455789056773
3.1998189225280393
5.352194176117621
3.323870881306003
1.6339110133361996
2.3006739698096172
6.343318933342674
4.423057748833315
2.0700237422276646
4.227563472687467
7.531693081454886
5.086871618486672
3.2697825054849563
3.7414674917724833
3.4668216820108873
2.9715225259124716
4.246022799946575
2.6306457133393573
1.4079006798306413
2.5948572319362175
1.9663247684016316
4.440496375910728
2.02324739489711
2.950873651904178
6.525963032240608
4.574010113833225
2.427709636499104
2.9240101539859573
1.974005164668974
1.7489109015427173
1.8837336523308654
3.26292799971747
2.5071624526369227
2.5187065093208005
5.641102739760913
2.2232209710724153
2.339818464592623
2.805632931756842
1.865287501728151
1.773280836332265
3.477294739617622
2.579646850117392
5.239997

1.1525338110515033
2.936068000516452
3.0943201612684392
1.6950157128819554
2.540842834329041
2.253930727507514
2.8684054372730428
2.4731162586915514
1.9193261065604388
2.045393044302412
1.3938589354765067
1.4924466110096821
1.5250124809065306
1.498333563248759
3.3476120169321066
1.3585042079414285
1.8164882861682907
1.5893384861788435
0.8922353357393303
2.509897842163829
2.0353651500107572
2.2027726925110507
1.5882291474554817
2.042470214834349
1.7627200162872514
1.6105438016992646
1.076612030565239
1.3506789558698107
2.480430561899554
2.221770066859717
1.1365102560472269
2.8528086902899057
1.9558177323383554
1.433570287862429
2.3138754142151345
1.5889434222710275
1.575964193654066
1.6378509103671406
0.982274222981171
3.1534810391882653
1.3071767890972972
1.0179038450109952
2.9325862419918938
1.7030126341504483
1.224951119684666
1.2239060502079635
2.5697423205036554
2.8819551250176163
2.538522173305184
1.3601805895919221
1.245895055534887
2.0709183410415966
1.7193453407932986
1.1218118

2.2536080201539206
1.0693169354213568
0.7743684199842409
0.542186851589789
0.47775730874215444
0.619869313219424
1.4095103816011016
1.9121438233119534
0.8398058826393264
0.7860108342801608
1.1473485683350289
1.5114775917746393
1.1592929120174214
1.0973915435085502
1.082737754503679
0.6144222436882067
1.08140066077737
1.6671739578792653
0.6760251986047112
0.9724090701256229
1.3426611271526232
1.5721581658178576
1.8121417849651091
1.5869563403204345
0.9557758922491455
1.193376349087497
1.0779537363369105
1.311627824993753
0.627581512603446
0.8798452421435996
1.501709593260684
1.8999695965021353
1.7832498610198977
1.6341735745714165
1.460275463317671
0.8515736703543081
2.365545700084877
0.5478406376877153
0.9372850858681898
0.6117701408709281
0.7503338460467657
0.990583035877622
0.9632629964013903
1.9871155313337354
0.9681903396644074
0.9591858800163251
1.1981138724361182
0.6650597438525492
1.409398563158447
2.7187679354629775
0.9747541372889921
1.024606505005695
1.4828410401342818
1.2996

0.6131793244393234
0.6437134155539799
0.7454255962068489
1.4010766953821934
1.424636663604292
1.6287178184580609
0.6343624918278179
0.7522945102416068
1.099067689876698
0.8325577264612474
1.140998569235018
0.797340648189762
1.4908709178549768
1.3601163251983996
1.1683548176885226
0.6635044677738328
1.2491470565456186
0.7326106436667399
0.4392988272996823
0.7080961384897635
1.1250481233402188
0.8027984954566683
1.1575645024982244
1.2708850187158731
0.5707578502885367
1.0316108051755914
1.0109205747672316
0.45137141491952437
0.9118020618862215
0.5284673555165191
1.0739145004619632
0.7781150170407924
0.44337941777681705
1.7018849768853537
1.650987222840406
1.9862775679761253
1.0615092780563171
0.471570985202761
1.6247515635463146
1.2678549196363293
0.9778360134245629
1.1980179837016363
0.9571864914406537
0.8815064866085803
1.2325182130438517
1.047218008990287
0.6161501223618466
0.6670811170436803
1.7144509017229228
1.6059705074270099
0.3958600219330823
0.8028034476179862
1.103510563039855

1.1556191200035064
1.482343591138793
1.2090757763746904
1.390453695614345
1.496968098295722
1.1148554908580581
2.0778284405759693
0.9118772985924616
1.465126994967878
2.2054728400335772
1.457387377764554
1.1271215507048016
0.7578526026106089
1.3501914819937637
1.295762259015876
1.5718159464948325
0.8777018235545793
1.1751765696913166
1.7235181087411744
0.6699585552124917
1.6893341428548962
1.1695547585364872
0.972178356338081
0.8010389818648828
1.714543000398601
1.4085435955358134
0.9980099187725819
1.4057377114395584
1.6107076626033514
1.118707587070873
1.0243548438902
1.2492245537459694
1.1593592480773909
1.494876868242628
0.9287360006925081
1.2743583777988718
2.2974377782648667
1.1115692047979118
1.5062596246180002
0.9574596236559715
0.99055613253696
1.2180376046347663
1.3575353599520286
1.041159652011281
1.2182847340990648
1.4183596547080901
0.7873377585726493
1.3863964443438257
1.944224550756285
1.0849354513067024
1.1197417095676505
1.5257297034784234
0.9343987505098292
1.72689656

2.491747450367698
2.825712952560824
3.184473203626661
2.605822182700363
2.8859236038901903
3.879110052489872
4.22148910597633
3.471638517381253
3.1608874076979614
2.3497462277096326
2.3975448596895452
3.5175736012116983
2.1182995206717536
2.6979577942475075
2.635357591897243
2.8459136941133094
4.222096738200831
2.276254340503695
3.6709825422259956
2.5608285886758297
3.376052243839696
5.071916990815739
3.5653257327894727
3.2010278134249788
4.4475330548764855
3.583457363201534
3.007033511386844
2.5553986339566412
3.289830520762415
6.463351793608901
2.7672166106111185
3.750897910519661
3.567079666456489
5.622052557123081
4.119182411272737
3.252603614967043
2.678131467665417
1.5222884765163922
2.291157091018363
2.24097086702103
3.9316889310270215
2.7589411783136004
2.5263358971031673
3.4659231371029398
2.2256474869283256
6.650824825471033
3.222506427382288
3.8011278341701455
3.3322116505764403
2.522864251632461
3.1747626407535785
3.239866574984838
3.7113155564317903
3.202427629859324
1.992

0.31301490762351764
0.38773927696542004
0.25661518420577406
0.8404677512804266
0.5454151573486504
0.482566674631869
0.31171571788993535
0.31944762578239655
0.3035827871469092
0.18567922793937408
0.3303923444834365
0.5765261269072031
0.33042392867174203
0.36672347108611697
0.833558858942306
0.20867246096115563
0.3186921459217864
0.23097945339814102
0.4362782949318997
0.8795542603951783
0.41341735917485795
0.3401251579375853
0.18839869712903262
0.6991794703508447
0.4450032491896241
0.3679909594213305
0.9606457030039649
0.8252289742551506
0.8322382390411557
0.39492372238259055
0.2416842849895467
0.5283414593233018
0.49513702835896517
0.46468454722828423
0.8061148844599527
0.3275503358488788
0.6490133924963206
0.6323057917146008
0.2749775087083436
0.26962244619877374
0.2531394691083796
0.7446960734338639
0.38523139779637017
0.20469118869875777
0.2747760226734095
0.29042398062586355
0.6120220891514725
0.7239533207666521
0.3180189067679475
0.16453954265505472
0.32398805398287606
0.6114202638

0.3501718914795473
0.3644396701784841
0.23242022817597854
0.4364815219237674
1.254265699111654
0.4009455416678195
0.39513532929540857
0.4887641897286805
1.2081058564606946
0.30527658941585695
0.3825084857450222
0.3339760903646031
0.32896590001082515
0.4897705386988737
1.6642029025047071
0.5496791140178118
0.3913742458947619
0.6173787890000157
1.0812856136013345
0.3461108766655968
0.339918491464479
0.5026793183433625
0.8355939115599429
1.2381918619192271
0.4321939846007631
0.46016555948135596
0.25160927140700745
0.5815527128860571
0.5498829490516827
1.0680535526685098
0.44817814752239205
0.2735411360671539
0.5204608691700612
0.9805953378424136
0.9412700808764208
0.5130252165725223
1.160254358363665
0.3270451068578023
0.9928174914539409
0.48259571441367044
0.2955562798026466
0.3285414658211668
0.7299363885120813
0.455360824905207
0.30504660693310726
0.3264915269841695
0.3642156757313594
1.3310466685575417
0.4615647383044458
0.8437199015544958
0.7276266682408257
0.652961149345672
0.623411

0.3949015143470199
0.308211417173756
0.5295822251170369
0.5276042680329723
0.315455882277469
0.34581350366958885
1.08781592387015
0.4436784649236577
0.653483838240158
0.4838235278029719
0.46348277788898945
0.6261805303352126
0.46688287878954876
1.4709096848443795
0.35647799634440547
0.45969126013883554
0.6391050439580033
0.3072166774325358
0.6203555881350062
0.7628130293015674
0.5029384199107122
0.40991988012677905
0.28720436999965604
0.31761458410827553
0.2588600578373841
0.5065705022023917
0.8063157187100658
0.3783801631596655
0.38807350238209715
0.3490601644170568
0.5493799152644985
0.5003815104462093
0.4969972826917974
0.5852778544282583
0.32704853191398364
0.45826853892123093
0.5399253424006988
0.3341930883966308
0.3237275107272534
0.6010753225371102
0.5392982239167994
0.644841841358529
1.0123798599254692
0.6050749762112569
0.4446346403290816
0.5685283389446009
0.5411575769874635
0.5331048753241729
0.35073353535586643
0.401980902143782
0.5460143382722781
0.9608227964029384
0.73443

0.43011297413468663
0.8951686206958782
1.0987247933710935
0.7848012928405129
0.701050802790397
0.7820025062878282
0.8979187822137016
0.8235231790227364
0.9232463875956238
0.43823807042529217
0.9634356249828764
0.67448325755444
1.153992783672174
0.7802183459053861
1.221078028401469
0.6561360309473824
1.344185810103894
0.45414495489909035
0.7025792411011444
0.9835013090543778
0.5460888605838594
1.4204404174931815
0.7343347446156585
0.6938905043897369
0.8321580496355192
0.8359870320505349
0.8873991207034359
1.0056693819054254
0.5085147290791523
0.5113484455577217
0.916025484156024
1.257430085315236
0.8112871086342949
1.2365775726356165
0.7559679718134209
1.4608872572076952
1.1145816348119018
0.5260297948839139
0.9000624119047194
0.6799043228114456
1.5111430269160326
0.9110554758126759
0.910743172912394
0.6989448701766819
1.1942751176028121
0.6635542347569995
0.7219392635781985
1.3794329265647285
0.5853924186945225
1.6870261376400637
0.5139849912787154
0.5512538597982416
0.7481838703502428