# Example for trying the algorithm and basic use of it

In [1]:
from SMILE.smile_ import SMiLE
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import KFold
import numpy as np

## Generate the data

In [2]:
X, y = make_multilabel_classification(n_samples=700)
X

array([[1., 0., 3., ..., 2., 2., 2.],
       [4., 3., 1., ..., 1., 3., 1.],
       [0., 2., 0., ..., 2., 3., 5.],
       ...,
       [4., 3., 1., ..., 0., 2., 0.],
       [4., 2., 2., ..., 2., 0., 2.],
       [2., 3., 2., ..., 4., 2., 2.]])

## Create the model and initialize it with the parameters we want

In [3]:
smile = SMiLE(s=0.5, alpha=0.35, k=5)

## Generate the partitions of the data for training and predict

In [4]:
skf = KFold(n_splits=2)
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

print(X_train)
print(X_test)

[[1. 0. 3. ... 2. 2. 2.]
 [4. 3. 1. ... 1. 3. 1.]
 [0. 2. 0. ... 2. 3. 5.]
 ...
 [4. 3. 2. ... 2. 2. 0.]
 [3. 2. 4. ... 0. 1. 0.]
 [1. 2. 2. ... 4. 0. 1.]]
[[4. 7. 5. ... 0. 3. 1.]
 [3. 0. 3. ... 2. 4. 1.]
 [2. 7. 1. ... 0. 0. 1.]
 ...
 [4. 3. 1. ... 0. 2. 0.]
 [4. 2. 2. ... 2. 0. 2.]
 [2. 3. 2. ... 4. 2. 2.]]


## Now we will train our model and predict, to compare the results

In [5]:
#This algorithm works with columns rather than with rows
X_train = np.transpose(X_train)
y_train = np.transpose(y_train)
X_test = np.transpose(X_test)
smile.fit(X_train, y_train)
predictions1, predictions2 = smile.predict(X_test)
print(y_train)
print(np.transpose(predictions1))
print(np.transpose(predictions2))
print(y_test)

[[0.99242424 0.26515152 0.88636364 0.70454545 0.64393939]
 [0.26923077 0.99230769 0.86923077 0.62307692 0.63846154]
 [0.25434783 0.24565217 0.99782609 0.57173913 0.61956522]
 [0.28181818 0.24545455 0.7969697  0.9969697  0.62121212]
 [0.22972973 0.22432432 0.77027027 0.55405405 0.9972973 ]]
[[0.         1.         1.         ... 0.         1.         1.        ]
 [0.         1.         0.70588235 ... 0.         0.59876543 0.68058968]
 [0.         1.         1.         ... 0.         1.         1.        ]
 [0.         1.         1.         ... 0.         1.         1.        ]
 [0.         1.         1.         ... 0.         0.26900268 1.        ]]
[[1. 4. 0. ... 4. 3. 1.]
 [0. 3. 2. ... 3. 2. 2.]
 [3. 1. 0. ... 2. 4. 2.]
 ...
 [2. 1. 2. ... 2. 0. 4.]
 [2. 3. 3. ... 2. 1. 0.]
 [2. 1. 5. ... 0. 0. 1.]]
[[0.89341655 0.67898671 0.79245603 0.69850778 0.7040598 ]
 [0.8526589  0.63822906 0.75169838 0.65775014 0.66330216]
 [0.85479227 0.64036242 0.75383175 0.6598835  0.66543552]
 ...
 [0.9134